version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=crypto_db
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/crypto_db?sslmode=disable
      - REDIS_ADDR=0.0.0.0:6379
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
volumes:
  data-volume: