#!/usr/bin/env bash
set -a
source "../app.env"
set +a

jq -n \
  --arg HTTP_SERVER_ADDR "$HTTP_SERVER_ADDR" \
  --arg GRPC_SERVER_ADDR "$GRPC_SERVER_ADDR" \
  --arg REDIS_ADDR "$REDIS_ADDR" \
  --arg MIGRATION_URL "$MIGRATION_URL" \
  --arg ACCESS_TOKEN_DURATION "$ACCESS_TOKEN_DURATION" \
  --arg REFRESH_TOKEN_DURATION "$REFRESH_TOKEN_DURATION" \
  --arg SENDER_NAME "$SENDER_NAME" \
  --arg SENDER_EMAIL "$SENDER_EMAIL" \
  --arg SENDER_PASSWORD "$SENDER_PASSWORD" \
  --arg ENVIRONMENT "$ENVIRONMENT" \
  --arg ORIGIN "$ORIGIN" \
  '{
    HTTP_SERVER_ADDR:$HTTP_SERVER_ADDR,
    GRPC_SERVER_ADDR:$GRPC_SERVER_ADDR,
    REDIS_ADDR:$REDIS_ADDR,
    MIGRATION_URL:$MIGRATION_URL,
    ACCESS_TOKEN_DURATION:$ACCESS_TOKEN_DURATION,
    REFRESH_TOKEN_DURATION:$REFRESH_TOKEN_DURATION,
    SENDER_NAME:$SENDER_NAME,
    SENDER_EMAIL:$SENDER_EMAIL,
    SENDER_PASSWORD:$SENDER_PASSWORD
    ENVIRONMENT:$ENVIRONMENT
    ORIGIN:$ORIGIN
  }'
