// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"github.com/google/uuid"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) GetAuditLogByID(context context.Context, d uuid.UUID) (any, error) {
	panic("unimplemented")
}

func (q *Queries) GetTradeByMarketID(context context.Context, d uuid.UUID) (any, error) {
	panic("unimplemented")
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
