// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: markets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createMarket = `-- name: CreateMarket :one
INSERT INTO markets (username, base_currency, quote_currency, min_order_amount, price_precision)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, base_currency, quote_currency, created_at
`

type CreateMarketParams struct {
	Username       string          `json:"username"`
	BaseCurrency   string          `json:"base_currency"`
	QuoteCurrency  string          `json:"quote_currency"`
	MinOrderAmount decimal.Decimal `json:"min_order_amount"`
	PricePrecision int32           `json:"price_precision"`
}

type CreateMarketRow struct {
	ID            uuid.UUID `json:"id"`
	Username      string    `json:"username"`
	BaseCurrency  string    `json:"base_currency"`
	QuoteCurrency string    `json:"quote_currency"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) CreateMarket(ctx context.Context, arg CreateMarketParams) (CreateMarketRow, error) {
	row := q.db.QueryRow(ctx, createMarket,
		arg.Username,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.MinOrderAmount,
		arg.PricePrecision,
	)
	var i CreateMarketRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMarket = `-- name: DeleteMarket :exec
DELETE FROM markets
WHERE id = $1
`

func (q *Queries) DeleteMarket(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMarket, id)
	return err
}

const getMarketByCurrencies = `-- name: GetMarketByCurrencies :one
SELECT id, username, base_currency, quote_currency, min_order_amount, price_precision, created_at
FROM markets
WHERE base_currency = $1 AND quote_currency = $2
`

type GetMarketByCurrenciesParams struct {
	BaseCurrency  string `json:"base_currency"`
	QuoteCurrency string `json:"quote_currency"`
}

func (q *Queries) GetMarketByCurrencies(ctx context.Context, arg GetMarketByCurrenciesParams) (Market, error) {
	row := q.db.QueryRow(ctx, getMarketByCurrencies, arg.BaseCurrency, arg.QuoteCurrency)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.MinOrderAmount,
		&i.PricePrecision,
		&i.CreatedAt,
	)
	return i, err
}

const getMarketByID = `-- name: GetMarketByID :one
SELECT id, username, base_currency, quote_currency, min_order_amount, price_precision, created_at
FROM markets
WHERE id = $1
`

func (q *Queries) GetMarketByID(ctx context.Context, id uuid.UUID) (Market, error) {
	row := q.db.QueryRow(ctx, getMarketByID, id)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.MinOrderAmount,
		&i.PricePrecision,
		&i.CreatedAt,
	)
	return i, err
}

const listMarketsByUsername = `-- name: ListMarketsByUsername :many
SELECT id, base_currency, quote_currency, min_order_amount, price_precision, created_at
FROM markets
WHERE username = $1
ORDER BY created_at DESC
`

type ListMarketsByUsernameRow struct {
	ID             uuid.UUID       `json:"id"`
	BaseCurrency   string          `json:"base_currency"`
	QuoteCurrency  string          `json:"quote_currency"`
	MinOrderAmount decimal.Decimal `json:"min_order_amount"`
	PricePrecision int32           `json:"price_precision"`
	CreatedAt      time.Time       `json:"created_at"`
}

func (q *Queries) ListMarketsByUsername(ctx context.Context, username string) ([]ListMarketsByUsernameRow, error) {
	rows, err := q.db.Query(ctx, listMarketsByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketsByUsernameRow
	for rows.Next() {
		var i ListMarketsByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.MinOrderAmount,
			&i.PricePrecision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
