// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (username, user_email, market_id, type, status, price, amount)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_email, market_id, type, status, price, amount, filled_amount, created_at, updated_at
`

type CreateOrderParams struct {
	Username  string      `json:"username"`
	UserEmail string      `json:"user_email"`
	MarketID  uuid.UUID   `json:"market_id"`
	Type      OrderType   `json:"type"`
	Status    OrderStatus `json:"status"`
	Price     string      `json:"price"`
	Amount    string      `json:"amount"`
}

type CreateOrderRow struct {
	ID           uuid.UUID   `json:"id"`
	UserEmail    string      `json:"user_email"`
	MarketID     uuid.UUID   `json:"market_id"`
	Type         OrderType   `json:"type"`
	Status       OrderStatus `json:"status"`
	Price        string      `json:"price"`
	Amount       string      `json:"amount"`
	FilledAmount string      `json:"filled_amount"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Username,
		arg.UserEmail,
		arg.MarketID,
		arg.Type,
		arg.Status,
		arg.Price,
		arg.Amount,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.MarketID,
		&i.Type,
		&i.Status,
		&i.Price,
		&i.Amount,
		&i.FilledAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, username, user_email, market_id, type, status, price, amount, filled_amount, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserEmail,
		&i.MarketID,
		&i.Type,
		&i.Status,
		&i.Price,
		&i.Amount,
		&i.FilledAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, username, user_email, market_id, type, status, price, amount, filled_amount, created_at, updated_at
FROM orders
ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UserEmail,
			&i.MarketID,
			&i.Type,
			&i.Status,
			&i.Price,
			&i.Amount,
			&i.FilledAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatusAndFilledAmount = `-- name: UpdateOrderStatusAndFilledAmount :exec
UPDATE orders
SET status = $1, filled_amount = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
`

type UpdateOrderStatusAndFilledAmountParams struct {
	Status       OrderStatus `json:"status"`
	FilledAmount string      `json:"filled_amount"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateOrderStatusAndFilledAmount(ctx context.Context, arg UpdateOrderStatusAndFilledAmountParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatusAndFilledAmount, arg.Status, arg.FilledAmount, arg.ID)
	return err
}
