// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateFee(ctx context.Context, arg CreateFeeParams) (CreateFeeRow, error)
	CreateMarket(ctx context.Context, arg CreateMarketParams) (CreateMarketRow, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteAuditLog(ctx context.Context, id uuid.UUID) error
	DeleteFee(ctx context.Context, id uuid.UUID) error
	DeleteMarket(ctx context.Context, id uuid.UUID) error
	DeleteOrder(ctx context.Context, id uuid.UUID) error
	DeleteTrade(ctx context.Context, id uuid.UUID) error
	DeleteTransaction(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWallet(ctx context.Context, id uuid.UUID) error
	GetAuditLogsByUserEmail(ctx context.Context, userEmail string) ([]AuditLog, error)
	GetFeeByMarketID(ctx context.Context, marketID uuid.UUID) (Fee, error)
	GetMarketByCurrencies(ctx context.Context, arg GetMarketByCurrenciesParams) (Market, error)
	GetMarketByID(ctx context.Context, id uuid.UUID) (Market, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetTradeByID(ctx context.Context, id uuid.UUID) (Trade, error)
	GetTradesByMarketID(ctx context.Context, marketID uuid.UUID) ([]Trade, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionsByUserEmail(ctx context.Context, userEmail string) ([]Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetWalletByID(ctx context.Context, id uuid.UUID) (Wallet, error)
	ListMarkets(ctx context.Context) ([]ListMarketsRow, error)
	UpdateOrderStatusAndFilledAmount(ctx context.Context, arg UpdateOrderStatusAndFilledAmountParams) error
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error
}

var _ Querier = (*Queries)(nil)
