// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: rpc_delete_transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_rpc_delete_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_delete_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type DeleteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionResponse) Reset() {
	*x = DeleteTransactionResponse{}
	mi := &file_rpc_delete_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionResponse) ProtoMessage() {}

func (x *DeleteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_delete_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteTransactionResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

var File_rpc_delete_transaction_proto protoreflect.FileDescriptor

const file_rpc_delete_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1crpc_delete_transaction.proto\x12\x02pb\"A\n" +
	"\x18DeleteTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"5\n" +
	"\x19DeleteTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\tR\asuccessB:Z8github.com/huzaifa678/Crypto-currency-web-app-project/pbb\x06proto3"

var (
	file_rpc_delete_transaction_proto_rawDescOnce sync.Once
	file_rpc_delete_transaction_proto_rawDescData []byte
)

func file_rpc_delete_transaction_proto_rawDescGZIP() []byte {
	file_rpc_delete_transaction_proto_rawDescOnce.Do(func() {
		file_rpc_delete_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_delete_transaction_proto_rawDesc), len(file_rpc_delete_transaction_proto_rawDesc)))
	})
	return file_rpc_delete_transaction_proto_rawDescData
}

var file_rpc_delete_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_delete_transaction_proto_goTypes = []any{
	(*DeleteTransactionRequest)(nil),  // 0: pb.DeleteTransactionRequest
	(*DeleteTransactionResponse)(nil), // 1: pb.DeleteTransactionResponse
}
var file_rpc_delete_transaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_delete_transaction_proto_init() }
func file_rpc_delete_transaction_proto_init() {
	if File_rpc_delete_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_delete_transaction_proto_rawDesc), len(file_rpc_delete_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_delete_transaction_proto_goTypes,
		DependencyIndexes: file_rpc_delete_transaction_proto_depIdxs,
		MessageInfos:      file_rpc_delete_transaction_proto_msgTypes,
	}.Build()
	File_rpc_delete_transaction_proto = out.File
	file_rpc_delete_transaction_proto_goTypes = nil
	file_rpc_delete_transaction_proto_depIdxs = nil
}
