// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: rpc_delete_market.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMarketRequest) Reset() {
	*x = DeleteMarketRequest{}
	mi := &file_rpc_delete_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMarketRequest) ProtoMessage() {}

func (x *DeleteMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMarketRequest.ProtoReflect.Descriptor instead.
func (*DeleteMarketRequest) Descriptor() ([]byte, []int) {
	return file_rpc_delete_market_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteMarketRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type DeleteMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMarketResponse) Reset() {
	*x = DeleteMarketResponse{}
	mi := &file_rpc_delete_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMarketResponse) ProtoMessage() {}

func (x *DeleteMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMarketResponse.ProtoReflect.Descriptor instead.
func (*DeleteMarketResponse) Descriptor() ([]byte, []int) {
	return file_rpc_delete_market_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteMarketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_delete_market_proto protoreflect.FileDescriptor

const file_rpc_delete_market_proto_rawDesc = "" +
	"\n" +
	"\x17rpc_delete_market.proto\x12\x02pb\"2\n" +
	"\x13DeleteMarketRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"0\n" +
	"\x14DeleteMarketResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB:Z8github.com/huzaifa678/Crypto-currency-web-app-project/pbb\x06proto3"

var (
	file_rpc_delete_market_proto_rawDescOnce sync.Once
	file_rpc_delete_market_proto_rawDescData []byte
)

func file_rpc_delete_market_proto_rawDescGZIP() []byte {
	file_rpc_delete_market_proto_rawDescOnce.Do(func() {
		file_rpc_delete_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_delete_market_proto_rawDesc), len(file_rpc_delete_market_proto_rawDesc)))
	})
	return file_rpc_delete_market_proto_rawDescData
}

var file_rpc_delete_market_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_delete_market_proto_goTypes = []any{
	(*DeleteMarketRequest)(nil),  // 0: pb.DeleteMarketRequest
	(*DeleteMarketResponse)(nil), // 1: pb.DeleteMarketResponse
}
var file_rpc_delete_market_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_delete_market_proto_init() }
func file_rpc_delete_market_proto_init() {
	if File_rpc_delete_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_delete_market_proto_rawDesc), len(file_rpc_delete_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_delete_market_proto_goTypes,
		DependencyIndexes: file_rpc_delete_market_proto_depIdxs,
		MessageInfos:      file_rpc_delete_market_proto_msgTypes,
	}.Build()
	File_rpc_delete_market_proto = out.File
	file_rpc_delete_market_proto_goTypes = nil
	file_rpc_delete_market_proto_depIdxs = nil
}
