// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: rpc_get_market_by_currencies.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMarketByCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency string                 `protobuf:"bytes,3,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketByCurrenciesRequest) Reset() {
	*x = GetMarketByCurrenciesRequest{}
	mi := &file_rpc_get_market_by_currencies_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketByCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketByCurrenciesRequest) ProtoMessage() {}

func (x *GetMarketByCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_market_by_currencies_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketByCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*GetMarketByCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_market_by_currencies_proto_rawDescGZIP(), []int{0}
}

func (x *GetMarketByCurrenciesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetMarketByCurrenciesRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetMarketByCurrenciesRequest) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

type GetMarketByCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *Market                `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketByCurrenciesResponse) Reset() {
	*x = GetMarketByCurrenciesResponse{}
	mi := &file_rpc_get_market_by_currencies_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketByCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketByCurrenciesResponse) ProtoMessage() {}

func (x *GetMarketByCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_market_by_currencies_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketByCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*GetMarketByCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_market_by_currencies_proto_rawDescGZIP(), []int{1}
}

func (x *GetMarketByCurrenciesResponse) GetMarket() *Market {
	if x != nil {
		return x.Market
	}
	return nil
}

var File_rpc_get_market_by_currencies_proto protoreflect.FileDescriptor

const file_rpc_get_market_by_currencies_proto_rawDesc = "" +
	"\n" +
	"\"rpc_get_market_by_currencies.proto\x12\x02pb\x1a\fmarket.proto\"\x86\x01\n" +
	"\x1cGetMarketByCurrenciesRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0equote_currency\x18\x03 \x01(\tR\rquoteCurrency\"C\n" +
	"\x1dGetMarketByCurrenciesResponse\x12\"\n" +
	"\x06market\x18\x01 \x01(\v2\n" +
	".pb.MarketR\x06marketB:Z8github.com/huzaifa678/Crypto-currency-web-app-project/pbb\x06proto3"

var (
	file_rpc_get_market_by_currencies_proto_rawDescOnce sync.Once
	file_rpc_get_market_by_currencies_proto_rawDescData []byte
)

func file_rpc_get_market_by_currencies_proto_rawDescGZIP() []byte {
	file_rpc_get_market_by_currencies_proto_rawDescOnce.Do(func() {
		file_rpc_get_market_by_currencies_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_market_by_currencies_proto_rawDesc), len(file_rpc_get_market_by_currencies_proto_rawDesc)))
	})
	return file_rpc_get_market_by_currencies_proto_rawDescData
}

var file_rpc_get_market_by_currencies_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_market_by_currencies_proto_goTypes = []any{
	(*GetMarketByCurrenciesRequest)(nil),  // 0: pb.GetMarketByCurrenciesRequest
	(*GetMarketByCurrenciesResponse)(nil), // 1: pb.GetMarketByCurrenciesResponse
	(*Market)(nil),                        // 2: pb.Market
}
var file_rpc_get_market_by_currencies_proto_depIdxs = []int32{
	2, // 0: pb.GetMarketByCurrenciesResponse.market:type_name -> pb.Market
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_market_by_currencies_proto_init() }
func file_rpc_get_market_by_currencies_proto_init() {
	if File_rpc_get_market_by_currencies_proto != nil {
		return
	}
	file_market_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_market_by_currencies_proto_rawDesc), len(file_rpc_get_market_by_currencies_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_market_by_currencies_proto_goTypes,
		DependencyIndexes: file_rpc_get_market_by_currencies_proto_depIdxs,
		MessageInfos:      file_rpc_get_market_by_currencies_proto_msgTypes,
	}.Build()
	File_rpc_get_market_by_currencies_proto = out.File
	file_rpc_get_market_by_currencies_proto_goTypes = nil
	file_rpc_get_market_by_currencies_proto_depIdxs = nil
}
