// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: rpc_get_order_by_market_id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrderByMarketIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByMarketIDRequest) Reset() {
	*x = GetOrderByMarketIDRequest{}
	mi := &file_rpc_get_order_by_market_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByMarketIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByMarketIDRequest) ProtoMessage() {}

func (x *GetOrderByMarketIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_order_by_market_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByMarketIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByMarketIDRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_order_by_market_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderByMarketIDRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type GetOrderByMarketIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByMarketIDResponse) Reset() {
	*x = GetOrderByMarketIDResponse{}
	mi := &file_rpc_get_order_by_market_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByMarketIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByMarketIDResponse) ProtoMessage() {}

func (x *GetOrderByMarketIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_order_by_market_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByMarketIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByMarketIDResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_order_by_market_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderByMarketIDResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_rpc_get_order_by_market_id_proto protoreflect.FileDescriptor

const file_rpc_get_order_by_market_id_proto_rawDesc = "" +
	"\n" +
	" rpc_get_order_by_market_id.proto\x12\x02pb\x1a\vorder.proto\"8\n" +
	"\x19GetOrderByMarketIDRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"?\n" +
	"\x1aGetOrderByMarketIDResponse\x12!\n" +
	"\x06orders\x18\x01 \x03(\v2\t.pb.OrderR\x06ordersB:Z8github.com/huzaifa678/Crypto-currency-web-app-project/pbb\x06proto3"

var (
	file_rpc_get_order_by_market_id_proto_rawDescOnce sync.Once
	file_rpc_get_order_by_market_id_proto_rawDescData []byte
)

func file_rpc_get_order_by_market_id_proto_rawDescGZIP() []byte {
	file_rpc_get_order_by_market_id_proto_rawDescOnce.Do(func() {
		file_rpc_get_order_by_market_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_order_by_market_id_proto_rawDesc), len(file_rpc_get_order_by_market_id_proto_rawDesc)))
	})
	return file_rpc_get_order_by_market_id_proto_rawDescData
}

var file_rpc_get_order_by_market_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_order_by_market_id_proto_goTypes = []any{
	(*GetOrderByMarketIDRequest)(nil),  // 0: pb.GetOrderByMarketIDRequest
	(*GetOrderByMarketIDResponse)(nil), // 1: pb.GetOrderByMarketIDResponse
	(*Order)(nil),                      // 2: pb.Order
}
var file_rpc_get_order_by_market_id_proto_depIdxs = []int32{
	2, // 0: pb.GetOrderByMarketIDResponse.orders:type_name -> pb.Order
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_order_by_market_id_proto_init() }
func file_rpc_get_order_by_market_id_proto_init() {
	if File_rpc_get_order_by_market_id_proto != nil {
		return
	}
	file_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_order_by_market_id_proto_rawDesc), len(file_rpc_get_order_by_market_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_order_by_market_id_proto_goTypes,
		DependencyIndexes: file_rpc_get_order_by_market_id_proto_depIdxs,
		MessageInfos:      file_rpc_get_order_by_market_id_proto_msgTypes,
	}.Build()
	File_rpc_get_order_by_market_id_proto = out.File
	file_rpc_get_order_by_market_id_proto_goTypes = nil
	file_rpc_get_order_by_market_id_proto_depIdxs = nil
}
