// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: rpc_google_login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginClient) Reset() {
	*x = LoginClient{}
	mi := &file_rpc_google_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginClient) ProtoMessage() {}

func (x *LoginClient) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_google_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginClient.ProtoReflect.Descriptor instead.
func (*LoginClient) Descriptor() ([]byte, []int) {
	return file_rpc_google_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginClient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginClient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginClient) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginClient) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginClient) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoginClient) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GoogleLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleLoginRequest) Reset() {
	*x = GoogleLoginRequest{}
	mi := &file_rpc_google_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginRequest) ProtoMessage() {}

func (x *GoogleLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_google_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginRequest.ProtoReflect.Descriptor instead.
func (*GoogleLoginRequest) Descriptor() ([]byte, []int) {
	return file_rpc_google_login_proto_rawDescGZIP(), []int{1}
}

func (x *GoogleLoginRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type GoogleLoginResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Client                *LoginClient           `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	AccessTokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GoogleLoginResponse) Reset() {
	*x = GoogleLoginResponse{}
	mi := &file_rpc_google_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginResponse) ProtoMessage() {}

func (x *GoogleLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_google_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginResponse.ProtoReflect.Descriptor instead.
func (*GoogleLoginResponse) Descriptor() ([]byte, []int) {
	return file_rpc_google_login_proto_rawDescGZIP(), []int{2}
}

func (x *GoogleLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GoogleLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GoogleLoginResponse) GetClient() *LoginClient {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *GoogleLoginResponse) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return nil
}

func (x *GoogleLoginResponse) GetRefreshTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return nil
}

var File_rpc_google_login_proto protoreflect.FileDescriptor

const file_rpc_google_login_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_google_login.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\vLoginClient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x12GoogleLoginRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\"\xae\x02\n" +
	"\x13GoogleLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12'\n" +
	"\x06client\x18\x03 \x01(\v2\x0f.pb.LoginClientR\x06client\x12Q\n" +
	"\x17access_token_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt\x12S\n" +
	"\x18refresh_token_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x15refreshTokenExpiresAtB:Z8github.com/huzaifa678/Crypto-currency-web-app-project/pbb\x06proto3"

var (
	file_rpc_google_login_proto_rawDescOnce sync.Once
	file_rpc_google_login_proto_rawDescData []byte
)

func file_rpc_google_login_proto_rawDescGZIP() []byte {
	file_rpc_google_login_proto_rawDescOnce.Do(func() {
		file_rpc_google_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_google_login_proto_rawDesc), len(file_rpc_google_login_proto_rawDesc)))
	})
	return file_rpc_google_login_proto_rawDescData
}

var file_rpc_google_login_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_google_login_proto_goTypes = []any{
	(*LoginClient)(nil),           // 0: pb.LoginClient
	(*GoogleLoginRequest)(nil),    // 1: pb.GoogleLoginRequest
	(*GoogleLoginResponse)(nil),   // 2: pb.GoogleLoginResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_rpc_google_login_proto_depIdxs = []int32{
	3, // 0: pb.LoginClient.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: pb.GoogleLoginResponse.client:type_name -> pb.LoginClient
	3, // 2: pb.GoogleLoginResponse.access_token_expires_at:type_name -> google.protobuf.Timestamp
	3, // 3: pb.GoogleLoginResponse.refresh_token_expires_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_google_login_proto_init() }
func file_rpc_google_login_proto_init() {
	if File_rpc_google_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_google_login_proto_rawDesc), len(file_rpc_google_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_google_login_proto_goTypes,
		DependencyIndexes: file_rpc_google_login_proto_depIdxs,
		MessageInfos:      file_rpc_google_login_proto_msgTypes,
	}.Build()
	File_rpc_google_login_proto = out.File
	file_rpc_google_login_proto_goTypes = nil
	file_rpc_google_login_proto_depIdxs = nil
}
