// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: rpc_update_order_status_and_filled_amount.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateOrderStatusAndFilledAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus   Status                 `protobuf:"varint,2,opt,name=order_status,json=orderStatus,proto3,enum=pb.Status" json:"order_status,omitempty"`
	FilledAmount  int64                  `protobuf:"varint,3,opt,name=filled_amount,json=filledAmount,proto3" json:"filled_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusAndFilledAmountRequest) Reset() {
	*x = UpdateOrderStatusAndFilledAmountRequest{}
	mi := &file_rpc_update_order_status_and_filled_amount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusAndFilledAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusAndFilledAmountRequest) ProtoMessage() {}

func (x *UpdateOrderStatusAndFilledAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_order_status_and_filled_amount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusAndFilledAmountRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusAndFilledAmountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_update_order_status_and_filled_amount_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateOrderStatusAndFilledAmountRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusAndFilledAmountRequest) GetOrderStatus() Status {
	if x != nil {
		return x.OrderStatus
	}
	return Status_OPEN
}

func (x *UpdateOrderStatusAndFilledAmountRequest) GetFilledAmount() int64 {
	if x != nil {
		return x.FilledAmount
	}
	return 0
}

type UpdateOrderStatusAndFilledAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusAndFilledAmountResponse) Reset() {
	*x = UpdateOrderStatusAndFilledAmountResponse{}
	mi := &file_rpc_update_order_status_and_filled_amount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusAndFilledAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusAndFilledAmountResponse) ProtoMessage() {}

func (x *UpdateOrderStatusAndFilledAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_order_status_and_filled_amount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusAndFilledAmountResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusAndFilledAmountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_order_status_and_filled_amount_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateOrderStatusAndFilledAmountResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

var File_rpc_update_order_status_and_filled_amount_proto protoreflect.FileDescriptor

const file_rpc_update_order_status_and_filled_amount_proto_rawDesc = "" +
	"\n" +
	"/rpc_update_order_status_and_filled_amount.proto\x12\x02pb\x1a\vorder.proto\"\x98\x01\n" +
	"'UpdateOrderStatusAndFilledAmountRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12-\n" +
	"\forder_status\x18\x02 \x01(\x0e2\n" +
	".pb.StatusR\vorderStatus\x12#\n" +
	"\rfilled_amount\x18\x03 \x01(\x03R\ffilledAmount\"D\n" +
	"(UpdateOrderStatusAndFilledAmountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\tR\asuccessB:Z8github.com/huzaifa678/Crypto-currency-web-app-project/pbb\x06proto3"

var (
	file_rpc_update_order_status_and_filled_amount_proto_rawDescOnce sync.Once
	file_rpc_update_order_status_and_filled_amount_proto_rawDescData []byte
)

func file_rpc_update_order_status_and_filled_amount_proto_rawDescGZIP() []byte {
	file_rpc_update_order_status_and_filled_amount_proto_rawDescOnce.Do(func() {
		file_rpc_update_order_status_and_filled_amount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_update_order_status_and_filled_amount_proto_rawDesc), len(file_rpc_update_order_status_and_filled_amount_proto_rawDesc)))
	})
	return file_rpc_update_order_status_and_filled_amount_proto_rawDescData
}

var file_rpc_update_order_status_and_filled_amount_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_order_status_and_filled_amount_proto_goTypes = []any{
	(*UpdateOrderStatusAndFilledAmountRequest)(nil),  // 0: pb.UpdateOrderStatusAndFilledAmountRequest
	(*UpdateOrderStatusAndFilledAmountResponse)(nil), // 1: pb.UpdateOrderStatusAndFilledAmountResponse
	(Status)(0), // 2: pb.Status
}
var file_rpc_update_order_status_and_filled_amount_proto_depIdxs = []int32{
	2, // 0: pb.UpdateOrderStatusAndFilledAmountRequest.order_status:type_name -> pb.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_update_order_status_and_filled_amount_proto_init() }
func file_rpc_update_order_status_and_filled_amount_proto_init() {
	if File_rpc_update_order_status_and_filled_amount_proto != nil {
		return
	}
	file_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_update_order_status_and_filled_amount_proto_rawDesc), len(file_rpc_update_order_status_and_filled_amount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_order_status_and_filled_amount_proto_goTypes,
		DependencyIndexes: file_rpc_update_order_status_and_filled_amount_proto_depIdxs,
		MessageInfos:      file_rpc_update_order_status_and_filled_amount_proto_msgTypes,
	}.Build()
	File_rpc_update_order_status_and_filled_amount_proto = out.File
	file_rpc_update_order_status_and_filled_amount_proto_goTypes = nil
	file_rpc_update_order_status_and_filled_amount_proto_depIdxs = nil
}
