// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: rpc_list_order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResponse) Reset() {
	*x = OrderListResponse{}
	mi := &file_rpc_list_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResponse) ProtoMessage() {}

func (x *OrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResponse.ProtoReflect.Descriptor instead.
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_list_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderListResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_rpc_list_order_proto protoreflect.FileDescriptor

const file_rpc_list_order_proto_rawDesc = "" +
	"\n" +
	"\x14rpc_list_order.proto\x12\x02pb\x1a\vorder.proto\"6\n" +
	"\x11OrderListResponse\x12!\n" +
	"\x06orders\x18\x01 \x03(\v2\t.pb.OrderR\x06ordersB:Z8github.com/huzaifa678/Crypto-currency-web-app-project/pbb\x06proto3"

var (
	file_rpc_list_order_proto_rawDescOnce sync.Once
	file_rpc_list_order_proto_rawDescData []byte
)

func file_rpc_list_order_proto_rawDescGZIP() []byte {
	file_rpc_list_order_proto_rawDescOnce.Do(func() {
		file_rpc_list_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_list_order_proto_rawDesc), len(file_rpc_list_order_proto_rawDesc)))
	})
	return file_rpc_list_order_proto_rawDescData
}

var file_rpc_list_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_list_order_proto_goTypes = []any{
	(*OrderListResponse)(nil), // 0: pb.OrderListResponse
	(*Order)(nil),             // 1: pb.Order
}
var file_rpc_list_order_proto_depIdxs = []int32{
	1, // 0: pb.OrderListResponse.orders:type_name -> pb.Order
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_list_order_proto_init() }
func file_rpc_list_order_proto_init() {
	if File_rpc_list_order_proto != nil {
		return
	}
	file_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_list_order_proto_rawDesc), len(file_rpc_list_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_list_order_proto_goTypes,
		DependencyIndexes: file_rpc_list_order_proto_depIdxs,
		MessageInfos:      file_rpc_list_order_proto_msgTypes,
	}.Build()
	File_rpc_list_order_proto = out.File
	file_rpc_list_order_proto_goTypes = nil
	file_rpc_list_order_proto_depIdxs = nil
}
