// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: rpc_get_transaction_by_user_email.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTransactionsByUserEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByUserEmailRequest) Reset() {
	*x = GetTransactionsByUserEmailRequest{}
	mi := &file_rpc_get_transaction_by_user_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByUserEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByUserEmailRequest) ProtoMessage() {}

func (x *GetTransactionsByUserEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_transaction_by_user_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByUserEmailRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByUserEmailRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_transaction_by_user_email_proto_rawDescGZIP(), []int{0}
}

func (x *GetTransactionsByUserEmailRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type GetTransactionsByUserEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByUserEmailResponse) Reset() {
	*x = GetTransactionsByUserEmailResponse{}
	mi := &file_rpc_get_transaction_by_user_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByUserEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByUserEmailResponse) ProtoMessage() {}

func (x *GetTransactionsByUserEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_transaction_by_user_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByUserEmailResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByUserEmailResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_transaction_by_user_email_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionsByUserEmailResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_rpc_get_transaction_by_user_email_proto protoreflect.FileDescriptor

const file_rpc_get_transaction_by_user_email_proto_rawDesc = "" +
	"\n" +
	"'rpc_get_transaction_by_user_email.proto\x12\x02pb\x1a\x11transaction.proto\"B\n" +
	"!GetTransactionsByUserEmailRequest\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\"Y\n" +
	"\"GetTransactionsByUserEmailResponse\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.pb.TransactionR\ftransactionsB:Z8github.com/huzaifa678/Crypto-currency-web-app-project/pbb\x06proto3"

var (
	file_rpc_get_transaction_by_user_email_proto_rawDescOnce sync.Once
	file_rpc_get_transaction_by_user_email_proto_rawDescData []byte
)

func file_rpc_get_transaction_by_user_email_proto_rawDescGZIP() []byte {
	file_rpc_get_transaction_by_user_email_proto_rawDescOnce.Do(func() {
		file_rpc_get_transaction_by_user_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_transaction_by_user_email_proto_rawDesc), len(file_rpc_get_transaction_by_user_email_proto_rawDesc)))
	})
	return file_rpc_get_transaction_by_user_email_proto_rawDescData
}

var file_rpc_get_transaction_by_user_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_transaction_by_user_email_proto_goTypes = []any{
	(*GetTransactionsByUserEmailRequest)(nil),  // 0: pb.GetTransactionsByUserEmailRequest
	(*GetTransactionsByUserEmailResponse)(nil), // 1: pb.GetTransactionsByUserEmailResponse
	(*Transaction)(nil),                        // 2: pb.Transaction
}
var file_rpc_get_transaction_by_user_email_proto_depIdxs = []int32{
	2, // 0: pb.GetTransactionsByUserEmailResponse.transactions:type_name -> pb.Transaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_transaction_by_user_email_proto_init() }
func file_rpc_get_transaction_by_user_email_proto_init() {
	if File_rpc_get_transaction_by_user_email_proto != nil {
		return
	}
	file_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_transaction_by_user_email_proto_rawDesc), len(file_rpc_get_transaction_by_user_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_transaction_by_user_email_proto_goTypes,
		DependencyIndexes: file_rpc_get_transaction_by_user_email_proto_depIdxs,
		MessageInfos:      file_rpc_get_transaction_by_user_email_proto_msgTypes,
	}.Build()
	File_rpc_get_transaction_by_user_email_proto = out.File
	file_rpc_get_transaction_by_user_email_proto_goTypes = nil
	file_rpc_get_transaction_by_user_email_proto_depIdxs = nil
}
