// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: service_crypto-web-app.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_crypto_web_app_proto protoreflect.FileDescriptor

const file_service_crypto_web_app_proto_rawDesc = "" +
	"\n" +
	"\x1cservice_crypto-web-app.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17rpc_create_market.proto\x1a\x17rpc_delete_market.proto\x1a\x14rpc_get_market.proto\x1a\x15rpc_list_market.proto\x1a\x16rpc_create_order.proto\x1a\x16rpc_delete_order.proto\x1a\x13rpc_get_order.proto\x1a\x15rpc_create_user.proto\x1a\x15rpc_delete_user.proto\x1a\x15rpc_update_user.proto\x1a\x12rpc_get_user.proto\x1a\x14rpc_login_user.proto\x1a\x17rpc_create_wallet.proto\x1a\x17rpc_delete_wallet.proto\x1a\x17rpc_update_wallet.proto\x1a\x14rpc_get_wallet.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xb9\v\n" +
	"\fCryptoWebApp\x12W\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12X\n" +
	"\n" +
	"DeleteUser\x12\x15.pb.DeleteUserRequest\x1a\x16.pb.DeleteUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/users/{user_id}\x12[\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/v1/users/{user_id}\x12O\n" +
	"\aGetUser\x12\x12.pb.GetUserRequest\x1a\x13.pb.GetUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/{user_id}\x12N\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12Y\n" +
	"\fCreateMarket\x12\x17.pb.CreateMarketRequest\x1a\x18.pb.CreateMarketResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/markets\x12b\n" +
	"\fDeleteMarket\x12\x17.pb.DeleteMarketRequest\x1a\x18.pb.DeleteMarketResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/markets/{market_id}\x12Y\n" +
	"\tGetMarket\x12\x14.pb.GetMarketRequest\x1a\x15.pb.GetMarketResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/markets/{market_id}\x12Q\n" +
	"\n" +
	"MarketList\x12\x16.google.protobuf.Empty\x1a\x16.pb.MarketListResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/markets\x12U\n" +
	"\vCreateOrder\x12\x16.pb.CreateOrderRequest\x1a\x17.pb.CreateOrderResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12]\n" +
	"\vDeleteOrder\x12\x16.pb.DeleteOrderRequest\x1a\x17.pb.DeleteOrderResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/orders/{order_id}\x12T\n" +
	"\bGetOrder\x12\x13.pb.GetOrderRequest\x1a\x14.pb.GetOrderResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/orders/{order_id}\x12Y\n" +
	"\fCreateWallet\x12\x17.pb.CreateWalletRequest\x1a\x18.pb.CreateWalletResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/wallets\x12b\n" +
	"\fDeleteWallet\x12\x17.pb.DeleteWalletRequest\x1a\x18.pb.DeleteWalletResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/wallets/{wallet_id}\x12e\n" +
	"\fUpdateWallet\x12\x17.pb.UpdateWalletRequest\x1a\x18.pb.UpdateWalletResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/v1/wallets/{wallet_id}\x12Y\n" +
	"\tGetWallet\x12\x14.pb.GetWalletRequest\x1a\x15.pb.GetWalletResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/wallets/{wallet_id}B\xa7\x01\x92Aj\x12h\n" +
	"\x12Crypto web app API\"M\n" +
	"\x12Huzaifa Ahmad Gill\x12\x1dhttps://github.com/huzaifa678\x1a\x18huzaifagill411@gmail.com2\x031.0Z8github.com/huzaifa678/Crypto-currency-web-app-project/pbb\x06proto3"

var file_service_crypto_web_app_proto_goTypes = []any{
	(*CreateUserRequest)(nil),    // 0: pb.CreateUserRequest
	(*DeleteUserRequest)(nil),    // 1: pb.DeleteUserRequest
	(*UpdateUserRequest)(nil),    // 2: pb.UpdateUserRequest
	(*GetUserRequest)(nil),       // 3: pb.GetUserRequest
	(*LoginUserRequest)(nil),     // 4: pb.LoginUserRequest
	(*CreateMarketRequest)(nil),  // 5: pb.CreateMarketRequest
	(*DeleteMarketRequest)(nil),  // 6: pb.DeleteMarketRequest
	(*GetMarketRequest)(nil),     // 7: pb.GetMarketRequest
	(*emptypb.Empty)(nil),        // 8: google.protobuf.Empty
	(*CreateOrderRequest)(nil),   // 9: pb.CreateOrderRequest
	(*DeleteOrderRequest)(nil),   // 10: pb.DeleteOrderRequest
	(*GetOrderRequest)(nil),      // 11: pb.GetOrderRequest
	(*CreateWalletRequest)(nil),  // 12: pb.CreateWalletRequest
	(*DeleteWalletRequest)(nil),  // 13: pb.DeleteWalletRequest
	(*UpdateWalletRequest)(nil),  // 14: pb.UpdateWalletRequest
	(*GetWalletRequest)(nil),     // 15: pb.GetWalletRequest
	(*CreateUserResponse)(nil),   // 16: pb.CreateUserResponse
	(*DeleteUserResponse)(nil),   // 17: pb.DeleteUserResponse
	(*UpdateUserResponse)(nil),   // 18: pb.UpdateUserResponse
	(*GetUserResponse)(nil),      // 19: pb.GetUserResponse
	(*LoginUserResponse)(nil),    // 20: pb.LoginUserResponse
	(*CreateMarketResponse)(nil), // 21: pb.CreateMarketResponse
	(*DeleteMarketResponse)(nil), // 22: pb.DeleteMarketResponse
	(*GetMarketResponse)(nil),    // 23: pb.GetMarketResponse
	(*MarketListResponse)(nil),   // 24: pb.MarketListResponse
	(*CreateOrderResponse)(nil),  // 25: pb.CreateOrderResponse
	(*DeleteOrderResponse)(nil),  // 26: pb.DeleteOrderResponse
	(*GetOrderResponse)(nil),     // 27: pb.GetOrderResponse
	(*CreateWalletResponse)(nil), // 28: pb.CreateWalletResponse
	(*DeleteWalletResponse)(nil), // 29: pb.DeleteWalletResponse
	(*UpdateWalletResponse)(nil), // 30: pb.UpdateWalletResponse
	(*GetWalletResponse)(nil),    // 31: pb.GetWalletResponse
}
var file_service_crypto_web_app_proto_depIdxs = []int32{
	0,  // 0: pb.CryptoWebApp.CreateUser:input_type -> pb.CreateUserRequest
	1,  // 1: pb.CryptoWebApp.DeleteUser:input_type -> pb.DeleteUserRequest
	2,  // 2: pb.CryptoWebApp.UpdateUser:input_type -> pb.UpdateUserRequest
	3,  // 3: pb.CryptoWebApp.GetUser:input_type -> pb.GetUserRequest
	4,  // 4: pb.CryptoWebApp.LoginUser:input_type -> pb.LoginUserRequest
	5,  // 5: pb.CryptoWebApp.CreateMarket:input_type -> pb.CreateMarketRequest
	6,  // 6: pb.CryptoWebApp.DeleteMarket:input_type -> pb.DeleteMarketRequest
	7,  // 7: pb.CryptoWebApp.GetMarket:input_type -> pb.GetMarketRequest
	8,  // 8: pb.CryptoWebApp.MarketList:input_type -> google.protobuf.Empty
	9,  // 9: pb.CryptoWebApp.CreateOrder:input_type -> pb.CreateOrderRequest
	10, // 10: pb.CryptoWebApp.DeleteOrder:input_type -> pb.DeleteOrderRequest
	11, // 11: pb.CryptoWebApp.GetOrder:input_type -> pb.GetOrderRequest
	12, // 12: pb.CryptoWebApp.CreateWallet:input_type -> pb.CreateWalletRequest
	13, // 13: pb.CryptoWebApp.DeleteWallet:input_type -> pb.DeleteWalletRequest
	14, // 14: pb.CryptoWebApp.UpdateWallet:input_type -> pb.UpdateWalletRequest
	15, // 15: pb.CryptoWebApp.GetWallet:input_type -> pb.GetWalletRequest
	16, // 16: pb.CryptoWebApp.CreateUser:output_type -> pb.CreateUserResponse
	17, // 17: pb.CryptoWebApp.DeleteUser:output_type -> pb.DeleteUserResponse
	18, // 18: pb.CryptoWebApp.UpdateUser:output_type -> pb.UpdateUserResponse
	19, // 19: pb.CryptoWebApp.GetUser:output_type -> pb.GetUserResponse
	20, // 20: pb.CryptoWebApp.LoginUser:output_type -> pb.LoginUserResponse
	21, // 21: pb.CryptoWebApp.CreateMarket:output_type -> pb.CreateMarketResponse
	22, // 22: pb.CryptoWebApp.DeleteMarket:output_type -> pb.DeleteMarketResponse
	23, // 23: pb.CryptoWebApp.GetMarket:output_type -> pb.GetMarketResponse
	24, // 24: pb.CryptoWebApp.MarketList:output_type -> pb.MarketListResponse
	25, // 25: pb.CryptoWebApp.CreateOrder:output_type -> pb.CreateOrderResponse
	26, // 26: pb.CryptoWebApp.DeleteOrder:output_type -> pb.DeleteOrderResponse
	27, // 27: pb.CryptoWebApp.GetOrder:output_type -> pb.GetOrderResponse
	28, // 28: pb.CryptoWebApp.CreateWallet:output_type -> pb.CreateWalletResponse
	29, // 29: pb.CryptoWebApp.DeleteWallet:output_type -> pb.DeleteWalletResponse
	30, // 30: pb.CryptoWebApp.UpdateWallet:output_type -> pb.UpdateWalletResponse
	31, // 31: pb.CryptoWebApp.GetWallet:output_type -> pb.GetWalletResponse
	16, // [16:32] is the sub-list for method output_type
	0,  // [0:16] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_crypto_web_app_proto_init() }
func file_service_crypto_web_app_proto_init() {
	if File_service_crypto_web_app_proto != nil {
		return
	}
	file_rpc_create_market_proto_init()
	file_rpc_delete_market_proto_init()
	file_rpc_get_market_proto_init()
	file_rpc_list_market_proto_init()
	file_rpc_create_order_proto_init()
	file_rpc_delete_order_proto_init()
	file_rpc_get_order_proto_init()
	file_rpc_create_user_proto_init()
	file_rpc_delete_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_get_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_create_wallet_proto_init()
	file_rpc_delete_wallet_proto_init()
	file_rpc_update_wallet_proto_init()
	file_rpc_get_wallet_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_crypto_web_app_proto_rawDesc), len(file_service_crypto_web_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_crypto_web_app_proto_goTypes,
		DependencyIndexes: file_service_crypto_web_app_proto_depIdxs,
	}.Build()
	File_service_crypto_web_app_proto = out.File
	file_service_crypto_web_app_proto_goTypes = nil
	file_service_crypto_web_app_proto_depIdxs = nil
}
