name: Terraform & AWS ECR Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

env:
  ENVIRONMENT: ${{ github.event.inputs.environment || github.ref_name }}
  BRANCH_TO_DEPLOY: ${{ github.event.inputs.environment || github.ref_name }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: ${{ env.BRANCH_TO_DEPLOY || 'main' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1 
      
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform
        
      - name: Terraform Plan
        run: |
          terraform plan \
            -var="google_client_id=${{ secrets.GOOGLE_CLIENT_ID }}" \
            -var="google_client_secret=${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            -var="token_symmetric_key=${{ secrets.TOKEN_SYMMETRIC_KEY }}" \
            -out=tfplan
        working-directory: ./terraform

      - name: Install Conftest
        run: |
          CONFTEST_VERSION=0.56.0
          curl -sSfL "https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz" \
            | sudo tar -xz -C /usr/local/bin conftest
          conftest --version

      - name: Policy as Code (OPA / Conftest)
        run: |
          terraform show -json tfplan > tfplan.json
          conftest test tfplan.json --policy policy --all-namespaces
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan
        working-directory: ./terraform

  docker:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Load secrets and save to app.env
        run: aws secretsmanager get-secret-value --secret-id production-credentials-v1 --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: crypto-ecr-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name crypto-system-eks-cluster

  delivery:
    name: Update Argo CD Application Image
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Generate Github App Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.GITOPS_APP_ID }}
          private-key: ${{ secrets.GITOPS_APP_PRIVATE_KEY }}
          owner: ${{ secrets.USER_NAME }}
          repositories: Continious-Delivery
          
      - name: Checkout GitOps Repository
        uses: actions/checkout@v7
        with:
          repository: ${{ secrets.USER_NAME }}/Continious-Delivery
          token: ${{ steps.app-token.outputs.token }}
          path: Continious-Delivery

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
         
      - name: Add Image Tag And Gateway NLB target
        run: |
          cd Continious-Delivery/eks-chart

          IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/crypto-ecr-repo:${{ github.sha }}"

          yq e -i '.image = "'$IMAGE'"' values.yaml
         
          NLB_DNS=$(aws elbv2 describe-load-balancers \
          --query "LoadBalancers[?Type=='network' && Scheme=='internet-facing'].DNSName | [0]" \
          --output text)

          yq e -i '.gateway.nlbTarget = "'$NLB_DNS'"' values.yaml

          
      - name: Commit and push changes
        run: |
          cd Continious-Delivery

          git config user.name "crypto-gitops-bot[bot]"
          git config user.email "${{ steps.app-token.outputs.installation-id }}+crypto-gitops-bot[bot]@users.noreply.github.com"

          git remote set-url origin \
            https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ secrets.USER_NAME }}/Continious-Delivery.git

          git add eks-chart/values.yaml
          git commit -m "deploy(crypto): image -> ${{ github.sha }}"
          git push -u origin main
