// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/huzaifa678/Crypto-currency-web-app-project/db/sqlc (interfaces: StoreInterface)

// Package mock_sqlc is a generated GoMock package.
package mock_sqlc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	db "github.com/huzaifa678/Crypto-currency-web-app-project/db/sqlc"
)

// MockStoreInterface is a mock of StoreInterface interface.
type MockStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStoreInterfaceMockRecorder
}

// MockStoreInterfaceMockRecorder is the mock recorder for MockStoreInterface.
type MockStoreInterfaceMockRecorder struct {
	mock *MockStoreInterface
}

// NewMockStoreInterface creates a new mock instance.
func NewMockStoreInterface(ctrl *gomock.Controller) *MockStoreInterface {
	mock := &MockStoreInterface{ctrl: ctrl}
	mock.recorder = &MockStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreInterface) EXPECT() *MockStoreInterfaceMockRecorder {
	return m.recorder
}

// CreateAuditLog mocks base method.
func (m *MockStoreInterface) CreateAuditLog(arg0 context.Context, arg1 db.CreateAuditLogParams) (db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", arg0, arg1)
	ret0, _ := ret[0].(db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockStoreInterfaceMockRecorder) CreateAuditLog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockStoreInterface)(nil).CreateAuditLog), arg0, arg1)
}

// CreateFee mocks base method.
func (m *MockStoreInterface) CreateFee(arg0 context.Context, arg1 db.CreateFeeParams) (db.CreateFeeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFee", arg0, arg1)
	ret0, _ := ret[0].(db.CreateFeeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFee indicates an expected call of CreateFee.
func (mr *MockStoreInterfaceMockRecorder) CreateFee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFee", reflect.TypeOf((*MockStoreInterface)(nil).CreateFee), arg0, arg1)
}

// CreateGoogleUser mocks base method.
func (m *MockStoreInterface) CreateGoogleUser(arg0 context.Context, arg1 db.CreateGoogleUserParams) (db.GoogleAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGoogleUser", arg0, arg1)
	ret0, _ := ret[0].(db.GoogleAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGoogleUser indicates an expected call of CreateGoogleUser.
func (mr *MockStoreInterfaceMockRecorder) CreateGoogleUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGoogleUser", reflect.TypeOf((*MockStoreInterface)(nil).CreateGoogleUser), arg0, arg1)
}

// CreateMarket mocks base method.
func (m *MockStoreInterface) CreateMarket(arg0 context.Context, arg1 db.CreateMarketParams) (db.CreateMarketRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMarket", arg0, arg1)
	ret0, _ := ret[0].(db.CreateMarketRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMarket indicates an expected call of CreateMarket.
func (mr *MockStoreInterfaceMockRecorder) CreateMarket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMarket", reflect.TypeOf((*MockStoreInterface)(nil).CreateMarket), arg0, arg1)
}

// CreateOrder mocks base method.
func (m *MockStoreInterface) CreateOrder(arg0 context.Context, arg1 db.CreateOrderParams) (db.CreateOrderRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1)
	ret0, _ := ret[0].(db.CreateOrderRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockStoreInterfaceMockRecorder) CreateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockStoreInterface)(nil).CreateOrder), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStoreInterface) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreInterfaceMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStoreInterface)(nil).CreateSession), arg0, arg1)
}

// CreateTrade mocks base method.
func (m *MockStoreInterface) CreateTrade(arg0 context.Context, arg1 db.CreateTradeParams) (db.Trade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrade", arg0, arg1)
	ret0, _ := ret[0].(db.Trade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTrade indicates an expected call of CreateTrade.
func (mr *MockStoreInterfaceMockRecorder) CreateTrade(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrade", reflect.TypeOf((*MockStoreInterface)(nil).CreateTrade), arg0, arg1)
}

// CreateTradeTx mocks base method.
func (m *MockStoreInterface) CreateTradeTx(arg0 context.Context, arg1 db.CreateTradeTxParams) (db.CreateTradeTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTradeTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreateTradeTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTradeTx indicates an expected call of CreateTradeTx.
func (mr *MockStoreInterfaceMockRecorder) CreateTradeTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTradeTx", reflect.TypeOf((*MockStoreInterface)(nil).CreateTradeTx), arg0, arg1)
}

// CreateTransaction mocks base method.
func (m *MockStoreInterface) CreateTransaction(arg0 context.Context, arg1 db.CreateTransactionParams) (db.CreateTransactionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", arg0, arg1)
	ret0, _ := ret[0].(db.CreateTransactionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockStoreInterfaceMockRecorder) CreateTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockStoreInterface)(nil).CreateTransaction), arg0, arg1)
}

// CreateTransactionForTransactionTypeTx mocks base method.
func (m *MockStoreInterface) CreateTransactionForTransactionTypeTx(arg0 context.Context, arg1 db.UpdateBalanceForTransactionTypeTxParams) (db.UpdateBalanceForTransactionTypeTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionForTransactionTypeTx", arg0, arg1)
	ret0, _ := ret[0].(db.UpdateBalanceForTransactionTypeTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransactionForTransactionTypeTx indicates an expected call of CreateTransactionForTransactionTypeTx.
func (mr *MockStoreInterfaceMockRecorder) CreateTransactionForTransactionTypeTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionForTransactionTypeTx", reflect.TypeOf((*MockStoreInterface)(nil).CreateTransactionForTransactionTypeTx), arg0, arg1)
}

// CreateTransactionTx mocks base method.
func (m *MockStoreInterface) CreateTransactionTx(arg0 context.Context, arg1 db.TransactionsParams, arg2 db.FeeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactionTx indicates an expected call of CreateTransactionTx.
func (mr *MockStoreInterfaceMockRecorder) CreateTransactionTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionTx", reflect.TypeOf((*MockStoreInterface)(nil).CreateTransactionTx), arg0, arg1, arg2)
}

// CreateUser mocks base method.
func (m *MockStoreInterface) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.CreateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.CreateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreInterfaceMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStoreInterface)(nil).CreateUser), arg0, arg1)
}

// CreateUserTx mocks base method.
func (m *MockStoreInterface) CreateUserTx(arg0 context.Context, arg1 db.CreateUserTxParams) (db.CreateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockStoreInterfaceMockRecorder) CreateUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockStoreInterface)(nil).CreateUserTx), arg0, arg1)
}

// CreateVerifyEmail mocks base method.
func (m *MockStoreInterface) CreateVerifyEmail(arg0 context.Context, arg1 db.CreateVerifyEmailParams) (db.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerifyEmail indicates an expected call of CreateVerifyEmail.
func (mr *MockStoreInterfaceMockRecorder) CreateVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyEmail", reflect.TypeOf((*MockStoreInterface)(nil).CreateVerifyEmail), arg0, arg1)
}

// CreateWallet mocks base method.
func (m *MockStoreInterface) CreateWallet(arg0 context.Context, arg1 db.CreateWalletParams) (db.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", arg0, arg1)
	ret0, _ := ret[0].(db.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockStoreInterfaceMockRecorder) CreateWallet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockStoreInterface)(nil).CreateWallet), arg0, arg1)
}

// DeleteAuditLog mocks base method.
func (m *MockStoreInterface) DeleteAuditLog(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuditLog", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuditLog indicates an expected call of DeleteAuditLog.
func (mr *MockStoreInterfaceMockRecorder) DeleteAuditLog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuditLog", reflect.TypeOf((*MockStoreInterface)(nil).DeleteAuditLog), arg0, arg1)
}

// DeleteFee mocks base method.
func (m *MockStoreInterface) DeleteFee(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFee", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFee indicates an expected call of DeleteFee.
func (mr *MockStoreInterfaceMockRecorder) DeleteFee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFee", reflect.TypeOf((*MockStoreInterface)(nil).DeleteFee), arg0, arg1)
}

// DeleteMarket mocks base method.
func (m *MockStoreInterface) DeleteMarket(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMarket", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMarket indicates an expected call of DeleteMarket.
func (mr *MockStoreInterfaceMockRecorder) DeleteMarket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMarket", reflect.TypeOf((*MockStoreInterface)(nil).DeleteMarket), arg0, arg1)
}

// DeleteOrder mocks base method.
func (m *MockStoreInterface) DeleteOrder(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockStoreInterfaceMockRecorder) DeleteOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockStoreInterface)(nil).DeleteOrder), arg0, arg1)
}

// DeleteTrade mocks base method.
func (m *MockStoreInterface) DeleteTrade(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrade", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrade indicates an expected call of DeleteTrade.
func (mr *MockStoreInterfaceMockRecorder) DeleteTrade(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrade", reflect.TypeOf((*MockStoreInterface)(nil).DeleteTrade), arg0, arg1)
}

// DeleteTransaction mocks base method.
func (m *MockStoreInterface) DeleteTransaction(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockStoreInterfaceMockRecorder) DeleteTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockStoreInterface)(nil).DeleteTransaction), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStoreInterface) DeleteUser(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreInterfaceMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStoreInterface)(nil).DeleteUser), arg0, arg1)
}

// DeleteWallet mocks base method.
func (m *MockStoreInterface) DeleteWallet(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWallet", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWallet indicates an expected call of DeleteWallet.
func (mr *MockStoreInterfaceMockRecorder) DeleteWallet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWallet", reflect.TypeOf((*MockStoreInterface)(nil).DeleteWallet), arg0, arg1)
}

// GetAuditLogsByUserEmail mocks base method.
func (m *MockStoreInterface) GetAuditLogsByUserEmail(arg0 context.Context, arg1 string) ([]db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditLogsByUserEmail", arg0, arg1)
	ret0, _ := ret[0].([]db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditLogsByUserEmail indicates an expected call of GetAuditLogsByUserEmail.
func (mr *MockStoreInterfaceMockRecorder) GetAuditLogsByUserEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditLogsByUserEmail", reflect.TypeOf((*MockStoreInterface)(nil).GetAuditLogsByUserEmail), arg0, arg1)
}

// GetFeeByMarketID mocks base method.
func (m *MockStoreInterface) GetFeeByMarketID(arg0 context.Context, arg1 uuid.UUID) (db.Fee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeeByMarketID", arg0, arg1)
	ret0, _ := ret[0].(db.Fee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeeByMarketID indicates an expected call of GetFeeByMarketID.
func (mr *MockStoreInterfaceMockRecorder) GetFeeByMarketID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeeByMarketID", reflect.TypeOf((*MockStoreInterface)(nil).GetFeeByMarketID), arg0, arg1)
}

// GetGoogleUserByEmail mocks base method.
func (m *MockStoreInterface) GetGoogleUserByEmail(arg0 context.Context, arg1 string) (db.GoogleAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoogleUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.GoogleAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoogleUserByEmail indicates an expected call of GetGoogleUserByEmail.
func (mr *MockStoreInterfaceMockRecorder) GetGoogleUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoogleUserByEmail", reflect.TypeOf((*MockStoreInterface)(nil).GetGoogleUserByEmail), arg0, arg1)
}

// GetGoogleUserByProviderID mocks base method.
func (m *MockStoreInterface) GetGoogleUserByProviderID(arg0 context.Context, arg1 string) (db.GoogleAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoogleUserByProviderID", arg0, arg1)
	ret0, _ := ret[0].(db.GoogleAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoogleUserByProviderID indicates an expected call of GetGoogleUserByProviderID.
func (mr *MockStoreInterfaceMockRecorder) GetGoogleUserByProviderID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoogleUserByProviderID", reflect.TypeOf((*MockStoreInterface)(nil).GetGoogleUserByProviderID), arg0, arg1)
}

// GetMarketByCurrencies mocks base method.
func (m *MockStoreInterface) GetMarketByCurrencies(arg0 context.Context, arg1 db.GetMarketByCurrenciesParams) (db.Market, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketByCurrencies", arg0, arg1)
	ret0, _ := ret[0].(db.Market)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketByCurrencies indicates an expected call of GetMarketByCurrencies.
func (mr *MockStoreInterfaceMockRecorder) GetMarketByCurrencies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketByCurrencies", reflect.TypeOf((*MockStoreInterface)(nil).GetMarketByCurrencies), arg0, arg1)
}

// GetMarketByID mocks base method.
func (m *MockStoreInterface) GetMarketByID(arg0 context.Context, arg1 uuid.UUID) (db.Market, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketByID", arg0, arg1)
	ret0, _ := ret[0].(db.Market)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketByID indicates an expected call of GetMarketByID.
func (mr *MockStoreInterfaceMockRecorder) GetMarketByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketByID", reflect.TypeOf((*MockStoreInterface)(nil).GetMarketByID), arg0, arg1)
}

// GetOrderByID mocks base method.
func (m *MockStoreInterface) GetOrderByID(arg0 context.Context, arg1 uuid.UUID) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockStoreInterfaceMockRecorder) GetOrderByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockStoreInterface)(nil).GetOrderByID), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockStoreInterface) GetSession(arg0 context.Context, arg1 uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreInterfaceMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStoreInterface)(nil).GetSession), arg0, arg1)
}

// GetTradeByID mocks base method.
func (m *MockStoreInterface) GetTradeByID(arg0 context.Context, arg1 uuid.UUID) (db.GetTradeByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTradeByID", arg0, arg1)
	ret0, _ := ret[0].(db.GetTradeByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTradeByID indicates an expected call of GetTradeByID.
func (mr *MockStoreInterfaceMockRecorder) GetTradeByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTradeByID", reflect.TypeOf((*MockStoreInterface)(nil).GetTradeByID), arg0, arg1)
}

// GetTradesByMarketID mocks base method.
func (m *MockStoreInterface) GetTradesByMarketID(arg0 context.Context, arg1 uuid.UUID) ([]db.GetTradesByMarketIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTradesByMarketID", arg0, arg1)
	ret0, _ := ret[0].([]db.GetTradesByMarketIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTradesByMarketID indicates an expected call of GetTradesByMarketID.
func (mr *MockStoreInterfaceMockRecorder) GetTradesByMarketID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTradesByMarketID", reflect.TypeOf((*MockStoreInterface)(nil).GetTradesByMarketID), arg0, arg1)
}

// GetTransactionByID mocks base method.
func (m *MockStoreInterface) GetTransactionByID(arg0 context.Context, arg1 uuid.UUID) (db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", arg0, arg1)
	ret0, _ := ret[0].(db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockStoreInterfaceMockRecorder) GetTransactionByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockStoreInterface)(nil).GetTransactionByID), arg0, arg1)
}

// GetTransactionsByUserEmail mocks base method.
func (m *MockStoreInterface) GetTransactionsByUserEmail(arg0 context.Context, arg1 string) ([]db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByUserEmail", arg0, arg1)
	ret0, _ := ret[0].([]db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByUserEmail indicates an expected call of GetTransactionsByUserEmail.
func (mr *MockStoreInterfaceMockRecorder) GetTransactionsByUserEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByUserEmail", reflect.TypeOf((*MockStoreInterface)(nil).GetTransactionsByUserEmail), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStoreInterface) GetUserByEmail(arg0 context.Context, arg1 string) (db.GetUserByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.GetUserByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreInterfaceMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStoreInterface)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockStoreInterface) GetUserByID(arg0 context.Context, arg1 uuid.UUID) (db.GetUserByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(db.GetUserByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStoreInterfaceMockRecorder) GetUserByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStoreInterface)(nil).GetUserByID), arg0, arg1)
}

// GetWalletByID mocks base method.
func (m *MockStoreInterface) GetWalletByID(arg0 context.Context, arg1 uuid.UUID) (db.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByID", arg0, arg1)
	ret0, _ := ret[0].(db.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByID indicates an expected call of GetWalletByID.
func (mr *MockStoreInterfaceMockRecorder) GetWalletByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByID", reflect.TypeOf((*MockStoreInterface)(nil).GetWalletByID), arg0, arg1)
}

// GetWalletsByUserEmail mocks base method.
func (m *MockStoreInterface) GetWalletsByUserEmail(arg0 context.Context, arg1 string) ([]db.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletsByUserEmail", arg0, arg1)
	ret0, _ := ret[0].([]db.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletsByUserEmail indicates an expected call of GetWalletsByUserEmail.
func (mr *MockStoreInterfaceMockRecorder) GetWalletsByUserEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletsByUserEmail", reflect.TypeOf((*MockStoreInterface)(nil).GetWalletsByUserEmail), arg0, arg1)
}

// ListMarketsByUsername mocks base method.
func (m *MockStoreInterface) ListMarketsByUsername(arg0 context.Context, arg1 string) ([]db.ListMarketsByUsernameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMarketsByUsername", arg0, arg1)
	ret0, _ := ret[0].([]db.ListMarketsByUsernameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMarketsByUsername indicates an expected call of ListMarketsByUsername.
func (mr *MockStoreInterfaceMockRecorder) ListMarketsByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMarketsByUsername", reflect.TypeOf((*MockStoreInterface)(nil).ListMarketsByUsername), arg0, arg1)
}

// ListOrdersByMarketID mocks base method.
func (m *MockStoreInterface) ListOrdersByMarketID(arg0 context.Context, arg1 uuid.UUID) ([]db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersByMarketID", arg0, arg1)
	ret0, _ := ret[0].([]db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrdersByMarketID indicates an expected call of ListOrdersByMarketID.
func (mr *MockStoreInterfaceMockRecorder) ListOrdersByMarketID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersByMarketID", reflect.TypeOf((*MockStoreInterface)(nil).ListOrdersByMarketID), arg0, arg1)
}

// ListOrdersByUsername mocks base method.
func (m *MockStoreInterface) ListOrdersByUsername(arg0 context.Context, arg1 string) ([]db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersByUsername", arg0, arg1)
	ret0, _ := ret[0].([]db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrdersByUsername indicates an expected call of ListOrdersByUsername.
func (mr *MockStoreInterfaceMockRecorder) ListOrdersByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersByUsername", reflect.TypeOf((*MockStoreInterface)(nil).ListOrdersByUsername), arg0, arg1)
}

// OrderForCurrencyTx mocks base method.
func (m *MockStoreInterface) OrderForCurrencyTx(arg0 context.Context, arg1 db.OrderForCurrencyTxParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderForCurrencyTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// OrderForCurrencyTx indicates an expected call of OrderForCurrencyTx.
func (mr *MockStoreInterfaceMockRecorder) OrderForCurrencyTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderForCurrencyTx", reflect.TypeOf((*MockStoreInterface)(nil).OrderForCurrencyTx), arg0, arg1)
}

// UpdateOrderStatusAndFilledAmount mocks base method.
func (m *MockStoreInterface) UpdateOrderStatusAndFilledAmount(arg0 context.Context, arg1 db.UpdateOrderStatusAndFilledAmountParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatusAndFilledAmount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatusAndFilledAmount indicates an expected call of UpdateOrderStatusAndFilledAmount.
func (mr *MockStoreInterfaceMockRecorder) UpdateOrderStatusAndFilledAmount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusAndFilledAmount", reflect.TypeOf((*MockStoreInterface)(nil).UpdateOrderStatusAndFilledAmount), arg0, arg1)
}

// UpdateTransactionStatus mocks base method.
func (m *MockStoreInterface) UpdateTransactionStatus(arg0 context.Context, arg1 db.UpdateTransactionStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionStatus indicates an expected call of UpdateTransactionStatus.
func (mr *MockStoreInterfaceMockRecorder) UpdateTransactionStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockStoreInterface)(nil).UpdateTransactionStatus), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStoreInterface) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreInterfaceMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStoreInterface)(nil).UpdateUser), arg0, arg1)
}

// UpdateVerifyEmail mocks base method.
func (m *MockStoreInterface) UpdateVerifyEmail(arg0 context.Context, arg1 db.UpdateVerifyEmailParams) (db.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVerifyEmail indicates an expected call of UpdateVerifyEmail.
func (mr *MockStoreInterfaceMockRecorder) UpdateVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerifyEmail", reflect.TypeOf((*MockStoreInterface)(nil).UpdateVerifyEmail), arg0, arg1)
}

// UpdateWalletBalance mocks base method.
func (m *MockStoreInterface) UpdateWalletBalance(arg0 context.Context, arg1 db.UpdateWalletBalanceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWalletBalance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWalletBalance indicates an expected call of UpdateWalletBalance.
func (mr *MockStoreInterfaceMockRecorder) UpdateWalletBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWalletBalance", reflect.TypeOf((*MockStoreInterface)(nil).UpdateWalletBalance), arg0, arg1)
}

// UpdatedOrderTx mocks base method.
func (m *MockStoreInterface) UpdatedOrderTx(arg0 context.Context, arg1 db.UpdatedOrderParams) (db.ReturnAmountParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedOrderTx", arg0, arg1)
	ret0, _ := ret[0].(db.ReturnAmountParams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatedOrderTx indicates an expected call of UpdatedOrderTx.
func (mr *MockStoreInterfaceMockRecorder) UpdatedOrderTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedOrderTx", reflect.TypeOf((*MockStoreInterface)(nil).UpdatedOrderTx), arg0, arg1)
}

// VerifyEmailTx mocks base method.
func (m *MockStoreInterface) VerifyEmailTx(arg0 context.Context, arg1 db.VerifyEmailTxParams) (db.VerifyEmailTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailTx", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmailTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailTx indicates an expected call of VerifyEmailTx.
func (mr *MockStoreInterfaceMockRecorder) VerifyEmailTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailTx", reflect.TypeOf((*MockStoreInterface)(nil).VerifyEmailTx), arg0, arg1)
}
