// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/huzaifa678/Crypto-currency-web-app-project/db/sqlc (interfaces: Store_interface)

// Package mock_sqlc is a generated GoMock package.
package mock_sqlc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	db "github.com/huzaifa678/Crypto-currency-web-app-project/db/sqlc"
)

// MockStore_interface is a mock of Store_interface interface.
type MockStore_interface struct {
	ctrl     *gomock.Controller
	recorder *MockStore_interfaceMockRecorder
}

// MockStore_interfaceMockRecorder is the mock recorder for MockStore_interface.
type MockStore_interfaceMockRecorder struct {
	mock *MockStore_interface
}

// NewMockStore_interface creates a new mock instance.
func NewMockStore_interface(ctrl *gomock.Controller) *MockStore_interface {
	mock := &MockStore_interface{ctrl: ctrl}
	mock.recorder = &MockStore_interfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore_interface) EXPECT() *MockStore_interfaceMockRecorder {
	return m.recorder
}

// CreateAuditLog mocks base method.
func (m *MockStore_interface) CreateAuditLog(arg0 context.Context, arg1 db.CreateAuditLogParams) (db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", arg0, arg1)
	ret0, _ := ret[0].(db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockStore_interfaceMockRecorder) CreateAuditLog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockStore_interface)(nil).CreateAuditLog), arg0, arg1)
}

// CreateFee mocks base method.
func (m *MockStore_interface) CreateFee(arg0 context.Context, arg1 db.CreateFeeParams) (db.Fee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFee", arg0, arg1)
	ret0, _ := ret[0].(db.Fee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFee indicates an expected call of CreateFee.
func (mr *MockStore_interfaceMockRecorder) CreateFee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFee", reflect.TypeOf((*MockStore_interface)(nil).CreateFee), arg0, arg1)
}

// CreateMarket mocks base method.
func (m *MockStore_interface) CreateMarket(arg0 context.Context, arg1 db.CreateMarketParams) (db.CreateMarketRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMarket", arg0, arg1)
	ret0, _ := ret[0].(db.CreateMarketRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMarket indicates an expected call of CreateMarket.
func (mr *MockStore_interfaceMockRecorder) CreateMarket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMarket", reflect.TypeOf((*MockStore_interface)(nil).CreateMarket), arg0, arg1)
}

// CreateOrder mocks base method.
func (m *MockStore_interface) CreateOrder(arg0 context.Context, arg1 db.CreateOrderParams) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockStore_interfaceMockRecorder) CreateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockStore_interface)(nil).CreateOrder), arg0, arg1)
}

// CreateTrade mocks base method.
func (m *MockStore_interface) CreateTrade(arg0 context.Context, arg1 db.CreateTradeParams) (db.Trade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrade", arg0, arg1)
	ret0, _ := ret[0].(db.Trade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTrade indicates an expected call of CreateTrade.
func (mr *MockStore_interfaceMockRecorder) CreateTrade(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrade", reflect.TypeOf((*MockStore_interface)(nil).CreateTrade), arg0, arg1)
}

// CreateTransaction mocks base method.
func (m *MockStore_interface) CreateTransaction(arg0 context.Context, arg1 db.CreateTransactionParams) (db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", arg0, arg1)
	ret0, _ := ret[0].(db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockStore_interfaceMockRecorder) CreateTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockStore_interface)(nil).CreateTransaction), arg0, arg1)
}

// CreateTransactionTx mocks base method.
func (m *MockStore_interface) CreateTransactionTx(arg0 context.Context, arg1 db.TransactionsParams, arg2 db.FeeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactionTx indicates an expected call of CreateTransactionTx.
func (mr *MockStore_interfaceMockRecorder) CreateTransactionTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionTx", reflect.TypeOf((*MockStore_interface)(nil).CreateTransactionTx), arg0, arg1, arg2)
}

// CreateUser mocks base method.
func (m *MockStore_interface) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.CreateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.CreateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStore_interfaceMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore_interface)(nil).CreateUser), arg0, arg1)
}

// CreateWallet mocks base method.
func (m *MockStore_interface) CreateWallet(arg0 context.Context, arg1 db.CreateWalletParams) (db.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", arg0, arg1)
	ret0, _ := ret[0].(db.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockStore_interfaceMockRecorder) CreateWallet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockStore_interface)(nil).CreateWallet), arg0, arg1)
}

// DeleteAuditLog mocks base method.
func (m *MockStore_interface) DeleteAuditLog(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuditLog", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuditLog indicates an expected call of DeleteAuditLog.
func (mr *MockStore_interfaceMockRecorder) DeleteAuditLog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuditLog", reflect.TypeOf((*MockStore_interface)(nil).DeleteAuditLog), arg0, arg1)
}

// DeleteFee mocks base method.
func (m *MockStore_interface) DeleteFee(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFee", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFee indicates an expected call of DeleteFee.
func (mr *MockStore_interfaceMockRecorder) DeleteFee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFee", reflect.TypeOf((*MockStore_interface)(nil).DeleteFee), arg0, arg1)
}

// DeleteMarket mocks base method.
func (m *MockStore_interface) DeleteMarket(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMarket", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMarket indicates an expected call of DeleteMarket.
func (mr *MockStore_interfaceMockRecorder) DeleteMarket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMarket", reflect.TypeOf((*MockStore_interface)(nil).DeleteMarket), arg0, arg1)
}

// DeleteOrder mocks base method.
func (m *MockStore_interface) DeleteOrder(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockStore_interfaceMockRecorder) DeleteOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockStore_interface)(nil).DeleteOrder), arg0, arg1)
}

// DeleteTrade mocks base method.
func (m *MockStore_interface) DeleteTrade(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrade", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrade indicates an expected call of DeleteTrade.
func (mr *MockStore_interfaceMockRecorder) DeleteTrade(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrade", reflect.TypeOf((*MockStore_interface)(nil).DeleteTrade), arg0, arg1)
}

// DeleteTransaction mocks base method.
func (m *MockStore_interface) DeleteTransaction(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockStore_interfaceMockRecorder) DeleteTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockStore_interface)(nil).DeleteTransaction), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStore_interface) DeleteUser(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStore_interfaceMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore_interface)(nil).DeleteUser), arg0, arg1)
}

// DeleteWallet mocks base method.
func (m *MockStore_interface) DeleteWallet(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWallet", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWallet indicates an expected call of DeleteWallet.
func (mr *MockStore_interfaceMockRecorder) DeleteWallet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWallet", reflect.TypeOf((*MockStore_interface)(nil).DeleteWallet), arg0, arg1)
}

// GetAuditLogsByUserEmail mocks base method.
func (m *MockStore_interface) GetAuditLogsByUserEmail(arg0 context.Context, arg1 string) ([]db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditLogsByUserEmail", arg0, arg1)
	ret0, _ := ret[0].([]db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditLogsByUserEmail indicates an expected call of GetAuditLogsByUserEmail.
func (mr *MockStore_interfaceMockRecorder) GetAuditLogsByUserEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditLogsByUserEmail", reflect.TypeOf((*MockStore_interface)(nil).GetAuditLogsByUserEmail), arg0, arg1)
}

// GetFeeByMarketID mocks base method.
func (m *MockStore_interface) GetFeeByMarketID(arg0 context.Context, arg1 uuid.UUID) (db.Fee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeeByMarketID", arg0, arg1)
	ret0, _ := ret[0].(db.Fee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeeByMarketID indicates an expected call of GetFeeByMarketID.
func (mr *MockStore_interfaceMockRecorder) GetFeeByMarketID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeeByMarketID", reflect.TypeOf((*MockStore_interface)(nil).GetFeeByMarketID), arg0, arg1)
}

// GetMarketByCurrencies mocks base method.
func (m *MockStore_interface) GetMarketByCurrencies(arg0 context.Context, arg1 db.GetMarketByCurrenciesParams) (db.Market, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketByCurrencies", arg0, arg1)
	ret0, _ := ret[0].(db.Market)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketByCurrencies indicates an expected call of GetMarketByCurrencies.
func (mr *MockStore_interfaceMockRecorder) GetMarketByCurrencies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketByCurrencies", reflect.TypeOf((*MockStore_interface)(nil).GetMarketByCurrencies), arg0, arg1)
}

// GetMarketByID mocks base method.
func (m *MockStore_interface) GetMarketByID(arg0 context.Context, arg1 uuid.UUID) (db.Market, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketByID", arg0, arg1)
	ret0, _ := ret[0].(db.Market)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketByID indicates an expected call of GetMarketByID.
func (mr *MockStore_interfaceMockRecorder) GetMarketByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketByID", reflect.TypeOf((*MockStore_interface)(nil).GetMarketByID), arg0, arg1)
}

// GetOrderByID mocks base method.
func (m *MockStore_interface) GetOrderByID(arg0 context.Context, arg1 uuid.UUID) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockStore_interfaceMockRecorder) GetOrderByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockStore_interface)(nil).GetOrderByID), arg0, arg1)
}

// GetTradeByID mocks base method.
func (m *MockStore_interface) GetTradeByID(arg0 context.Context, arg1 uuid.UUID) (db.Trade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTradeByID", arg0, arg1)
	ret0, _ := ret[0].(db.Trade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTradeByID indicates an expected call of GetTradeByID.
func (mr *MockStore_interfaceMockRecorder) GetTradeByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTradeByID", reflect.TypeOf((*MockStore_interface)(nil).GetTradeByID), arg0, arg1)
}

// GetTradesByMarketID mocks base method.
func (m *MockStore_interface) GetTradesByMarketID(arg0 context.Context, arg1 uuid.UUID) ([]db.Trade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTradesByMarketID", arg0, arg1)
	ret0, _ := ret[0].([]db.Trade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTradesByMarketID indicates an expected call of GetTradesByMarketID.
func (mr *MockStore_interfaceMockRecorder) GetTradesByMarketID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTradesByMarketID", reflect.TypeOf((*MockStore_interface)(nil).GetTradesByMarketID), arg0, arg1)
}

// GetTransactionByID mocks base method.
func (m *MockStore_interface) GetTransactionByID(arg0 context.Context, arg1 uuid.UUID) (db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", arg0, arg1)
	ret0, _ := ret[0].(db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockStore_interfaceMockRecorder) GetTransactionByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockStore_interface)(nil).GetTransactionByID), arg0, arg1)
}

// GetTransactionsByUserEmail mocks base method.
func (m *MockStore_interface) GetTransactionsByUserEmail(arg0 context.Context, arg1 string) ([]db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByUserEmail", arg0, arg1)
	ret0, _ := ret[0].([]db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByUserEmail indicates an expected call of GetTransactionsByUserEmail.
func (mr *MockStore_interfaceMockRecorder) GetTransactionsByUserEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByUserEmail", reflect.TypeOf((*MockStore_interface)(nil).GetTransactionsByUserEmail), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore_interface) GetUserByEmail(arg0 context.Context, arg1 string) (db.GetUserByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.GetUserByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStore_interfaceMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore_interface)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockStore_interface) GetUserByID(arg0 context.Context, arg1 uuid.UUID) (db.GetUserByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(db.GetUserByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStore_interfaceMockRecorder) GetUserByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStore_interface)(nil).GetUserByID), arg0, arg1)
}

// GetWalletByUserEmailAndCurrency mocks base method.
func (m *MockStore_interface) GetWalletByUserEmailAndCurrency(arg0 context.Context, arg1 db.GetWalletByUserEmailAndCurrencyParams) (db.GetWalletByUserEmailAndCurrencyRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByUserEmailAndCurrency", arg0, arg1)
	ret0, _ := ret[0].(db.GetWalletByUserEmailAndCurrencyRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByUserEmailAndCurrency indicates an expected call of GetWalletByUserEmailAndCurrency.
func (mr *MockStore_interfaceMockRecorder) GetWalletByUserEmailAndCurrency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByUserEmailAndCurrency", reflect.TypeOf((*MockStore_interface)(nil).GetWalletByUserEmailAndCurrency), arg0, arg1)
}

// ListMarkets mocks base method.
func (m *MockStore_interface) ListMarkets(arg0 context.Context) ([]db.Market, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMarkets", arg0)
	ret0, _ := ret[0].([]db.Market)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMarkets indicates an expected call of ListMarkets.
func (mr *MockStore_interfaceMockRecorder) ListMarkets(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMarkets", reflect.TypeOf((*MockStore_interface)(nil).ListMarkets), arg0)
}

// UpdateOrderStatusAndFilledAmount mocks base method.
func (m *MockStore_interface) UpdateOrderStatusAndFilledAmount(arg0 context.Context, arg1 db.UpdateOrderStatusAndFilledAmountParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatusAndFilledAmount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatusAndFilledAmount indicates an expected call of UpdateOrderStatusAndFilledAmount.
func (mr *MockStore_interfaceMockRecorder) UpdateOrderStatusAndFilledAmount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusAndFilledAmount", reflect.TypeOf((*MockStore_interface)(nil).UpdateOrderStatusAndFilledAmount), arg0, arg1)
}

// UpdateTransactionStatus mocks base method.
func (m *MockStore_interface) UpdateTransactionStatus(arg0 context.Context, arg1 db.UpdateTransactionStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionStatus indicates an expected call of UpdateTransactionStatus.
func (mr *MockStore_interfaceMockRecorder) UpdateTransactionStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockStore_interface)(nil).UpdateTransactionStatus), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore_interface) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStore_interfaceMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore_interface)(nil).UpdateUser), arg0, arg1)
}

// UpdateWalletBalance mocks base method.
func (m *MockStore_interface) UpdateWalletBalance(arg0 context.Context, arg1 db.UpdateWalletBalanceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWalletBalance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWalletBalance indicates an expected call of UpdateWalletBalance.
func (mr *MockStore_interfaceMockRecorder) UpdateWalletBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWalletBalance", reflect.TypeOf((*MockStore_interface)(nil).UpdateWalletBalance), arg0, arg1)
}

// UpdatedOrderTx mocks base method.
func (m *MockStore_interface) UpdatedOrderTx(arg0 context.Context, arg1 db.UpdatedOrderParams) (db.ReturnAmountParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedOrderTx", arg0, arg1)
	ret0, _ := ret[0].(db.ReturnAmountParams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatedOrderTx indicates an expected call of UpdatedOrderTx.
func (mr *MockStore_interfaceMockRecorder) UpdatedOrderTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedOrderTx", reflect.TypeOf((*MockStore_interface)(nil).UpdatedOrderTx), arg0, arg1)
}
